spring:
  datasource:
    url: ${DB_URL2}
    username: ${DB_USERNAME2}
    password: ${DB_PASSWORD2}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  error:
    include-message: always
  port: 8000

jwt:
  secret:
    key: ${SECRET_KEY}